# Site settings
title: Supernote Docs (Unofficial)
author:
  name: Rescue Ferret
  email: rescueferret88@gmail.com
description: "Documentation about Supernote X and X2 series tablets. Not affiliated with Ratta Supernote."

# Build settings
remote_theme: jekyll/minima
